### PR TITLE
Updates to height-map documentation

### PR DESCRIPTION
**Pull request by sokorototo**
Cleared some spelling and grammar mistakes, I think. Reduced the amount of information delivered for a more streamlined learning experience. Changed code examples to use cleaner more readable code. Removed `var` in favor of `const`. Changed structure of the document a little bit.

### CODE REVIEW

**Comment by RaananW** [comment]
@PirateJC - would be great to get your review here.

Just a question from me - why have you decided to remove so much of the content?

**Comment by sokorototo** [comment]
Because as I was passing through the docs I noticed the information was kind of unfocused. So I made a PR and made some adjustments. I tried my best to hit all the important information. Maybe you can tell me what important points I missed in specific. I also added some information, from the API docs.

**Comment by sebavan** [comment]
Agree that it sounds weird to lose some info

**Comment by sokorototo** [comment]
What important info has been lost?

**Comment by sebavan** [comment]
Like the camera tips code for instance. I ll let @PirateJC as he is way more aware than me about the doc progression

**Comment by sokorototo** [comment]
I think that it was unrelated to the topic at hand, and should most likely be in another chapter. A "tips and tricks" chapter for example. Things like preventing clipping into the height map could be discussed.

**Comment by PirateJC** [comment]
Just read through this new version and I honestly think it's a fantastic improvement! It reads more clearly and helps build the information better than in the previous iteration. Fantastic work @sokorototo! You clearly have a gift for this!

I tend to agree I actually don't think the camera piece is a critical part of this particular doc, more of an "additional topic."

My only ask before we merge is to add links to when you mention Terragen and Picogen. @sokorototo would you mind doing the honors for that?

Other than that I think it's a nice rewrite of the doc. Again great work!

**Comment by sokorototo** [comment]
Yeah sure

**Comment by sokorototo** [comment]
I have now added download links to Terragen's and Picogen's download pages. Thanks for all the feedback guys

**Review by PirateJC — APPROVED** [review]
Awesome! Approved! Thank you so much for doing this awesome pass! Fantastic work!

**Pull request merged**
