### PR TITLE
Add missing or incorrect shadow troubleshooting info

### PR DESCRIPTION
**Pull request by AJamesPhillips**
Copied from this question: https://forum.babylonjs.com/t/how-to-fix-shadow-shape/28580

### CODE REVIEW

**Comment by AJamesPhillips** [comment]
Actually we should either:

1. put a link to the question so that if the image URL changes then someone can more easily find the original image and optionally update it to fix it.
2. or put this / another image into this repo

**Comment by RaananW** [comment]
Thank you so much for that :-)

This is one of many reasons as to why you don't see your shadows. Whereas this is a great start, I don't want people to think this is the only thing they can try if their shadows don't work. This should probably expand a little more. Maybe instead of a very abstract title we can add a sentence saying it is possible to try if you are having difficulties with the shadows as part of the text before the newly added section?

**Comment by AJamesPhillips** [comment]
> Thank you so much for that :-)

My pleasure :)

> This is one of many reasons as to why you don't see your shadows. Whereas this is a great start, I don't want people to think this is the only thing they can try if their shadows don't work.
> This should probably expand a little more.

Yes sorry I do not know of any of the other approaches to fixing missing shadows.

> Maybe instead of a very abstract title we can add a sentence saying it is possible to try if you are having difficulties with the shadows as part of the text before the newly added section?

Sorry I do not know how to improve it, could you do this please?  Or I will be happy to update the PR with some text you write here.

**Comment by RaananW** [comment]
Closing this for now, but I totally understand the need for that. I'll create an issue and see how we tackle this.

**Pull request closed without merging**
