### PR TITLE
Additional help added to Vite Basics tutorial

### PR DESCRIPTION
**Pull request by wavetro**
Added some extra instructions for vanilla JS users for my [Vite](https://doc.babylonjs.com/guidedLearning/usingVite) guide on the docs!

### CODE REVIEW

**Comment by RaananW** [comment]
I am not sure how much these changes are needed? The code is technically the same, but without types. The other changes are cosmetic.
A short sentence stating that JavaScript users will need to remove the types would be enough, no? Or am I missing something?

**Comment by wavetro** [comment]
@RaananW The original tutorial was written for very new programmers who are only familiar with coding the Start Your Journey chapters in the Playground, and don't know how to move that knowledge into an IDE or code editor. I then had someone approach me who's been learning JavaScript for the first time by learning Babylon (who wanted a non-TS version of this documentation,) so putting an entire JS version of the code here also doubles as a way to show those readers that TS is not very different from JS.

Let me know if you still want me to condense this into simpler instructions though!

**Comment by RaananW** [comment]
This will be a very confusing tutorial for someone who is just getting starting with JavaScript. It's not that i mind having it, i just think the way it's presented it's not helping as it should. If you are providing a JavaScript tutorial, do it fully. Otherwise newcomers will be lost. "Do this step, but if you are using JavaScript do what's in the parenthesis, except for step 9, which you  should copy from down below".

Just my two cents, to be honest. If you say that you think this is the right way to go I'll approve it and merge it.

**Comment by wavetro** [comment]
Fair point, would it be better if I just link to the forum post with all the differing instructions for JavaScript users? It would be cleaner than trying to implement them directly into the same page as the TypeScript instructions like I tried to do here

**Pull request closed without merging**
