### PR TITLE
Update HowToContribute.md

### PR DESCRIPTION
**Pull request by RolandCsibrei**
Windows access denied on port 1337 troubleshooting

### CODE REVIEW

**Comment by sebavan** [comment]
Interesting, I never ran into this :-) Adding @RaananW as I am not sure reset winnat is smthg we should advise on the doc without detailing what could go wrong ?

**Comment by RaananW** [comment]
I totally agree with @sebavan. This is a local issue that is very system-dependent. I have never experienced that (and AFAIK no one from the team as well. This is the first time I enouncter an issue with a system that blocks access to port 1337. Might be a local firewall issue?
Anyhow - we shouldn't suggest resetting winnat in our official docs. this is an issue we can resolve on the forum based on the user's comment.

**Comment by RolandCsibrei** [comment]
Guys, I was struggling to get it working for 3 hours. I tried different node versions,  I even uninstalled my antivirus despite I was double checking port usages, I wrote a simple node app to test whether it can connect to port 1337, I got through all recomendations I found on Google. The port was not used. The antivirus was not blocking the port. This solution worked. I suggest to leave this solution in the offcials docs but add some information what can the user check before triying this the last if nothing worked. How about that?

**Comment by sebavan** [comment]
I am not against adding it in a troubleshooting note but we need an explanation of why and what can break doing this so at least ppl understand the risk if any ?

**Pull request closed without merging**
