### PR TITLE
Update Gui.md

### PR DESCRIPTION
**Pull request by BlakeOne**
Add a note about manual resizing to the adaptive scaling section of the GUI documentation.

Forum: https://forum.babylonjs.com/t/introducing-the-gui-editor-alpha/24578/80

### CODE REVIEW

**Comment by BlakeOne** [comment]
Or maybe it should say "rescaling" instead of "resizing"? :)

**Comment by msDestiny14** [comment]
I don't know if you need the parenthesis but just my opinion.

**Comment by BlakeOne** [comment]
I went back and forth a bit and got it into my head that it sounded friendlier with the parenthesis somehow, LOL. Here it is without them thou. :)

The grammar checker said you'll would be more friendly than you will - I didn't think it sounded as good, but they got into my head, LOL. ;)

**Comment by msDestiny14** [comment]
Also maybe I'm being very nitty on the wording but what what does this mean? "resizing strategy used". If I had no idea about anything Babylon what would this mean to me. I guess the biggest advice for documentation is assuming the reader may not have knowledge.

**Comment by BlakeOne** [comment]
To me examples of resizing strategies would be "scale by min dimension", "scale by width", etc. It's whatever strategy you want to use for resizing.  It's more of a general-purpose CG term that I've read and used before thou, not Babylon specific per se...

I'm def not married to it thou. :)

**Comment by BlakeOne** [comment]
Here it is with just the one, simpler line. :)

**Review by sebavan — APPROVED** [review]

**Pull request merged**
