### PR TITLE
Revise the "diving deeper" (howto) page on reflections & refractions

### PR DESCRIPTION
**Pull request by egnor**
This is written to clarify a number of issues that confused me originally, including the relationship with skyboxes, the different types of texture, the impact of coordinate modes, and the overall approach used (along with caveats of different choices).

Please check it over -- hopefully it's mostly accurate!

### CODE REVIEW

**Comment by RaananW** [comment]
@PirateJC  - I leave this one in your caring hands

**Review by RaananW — CHANGES_REQUESTED** [review]
I'm going to let @PirateJC review regarding the content, but I'll have to ask to organize the pr and make sure you only commit the changes. I don't know what happened, but you seem to be committing the same changes that are already merged. Both this and the other PR have the same issue

**Comment by egnor** [comment]
> I'm going to let @PirateJC review regarding the content, but I'll have to ask to organize the pr and make sure you only commit the changes. I don't know what happened, but you seem to be committing the same changes that are already merged. Both this and the other PR have the same issue

Sorry about that, I did a merge (to catch up with the tree) where I probably should have done a rebase and force push. I'll endeavor to clean it up.

**Comment by egnor** [comment]
> I'm going to let @PirateJC review regarding the content, but I'll have to ask to organize the pr and make sure you only commit the changes. I don't know what happened, but you seem to be committing the same changes that are already merged. Both this and the other PR have the same issue

Rebased, squashed into a single commit, should be sane now. Sorry again, git is not my native language :-)

**Comment by sebavan** [comment]
@RaananW and @PirateJC do you think it is good to go ?

**Comment by RaananW** [comment]
I'll check with @PirateJC

**Review by PirateJC — APPROVED** [review]

**Review by RaananW — APPROVED** [review]

**Pull request merged**
