### PR TITLE
Added BabylonJS with Vue tutorial

### PR DESCRIPTION
**Pull request by RolandCsibrei**

### CODE REVIEW

**Comment by sebavan** [comment]
LGTM adding @PirateJC to double check and merge ?

**Review by PirateJC — APPROVED** [review]
Looks Awesome!

**Comment by PirateJC** [comment]
Fantastic job @RolandCsibrei 

Really nicely written doc! 

Thanks so much for contributing!!!!

**Comment by RolandCsibrei** [comment]
Thanks JC!On Jul 6, 2021 5:33 PM, PirateJC ***@***.***> wrote:
Fantastic job @RolandCsibrei
Really nicely written doc!
Thanks so much for contributing!!!!

**Pull request merged**
