### PR TITLE
Update sitemaps and typedoc generation

### PR DESCRIPTION
**Pull request by RaananW**

### CODE REVIEW

**Comment by Popov72** [comment]
Is an empty picture for `public/img/playgroundsAndNMEs/pg-PCY1J-299.png` the expected result?

**Comment by RaananW** [comment]
> Is an empty picture for `public/img/playgroundsAndNMEs/pg-PCY1J-299.png` the expected result?

good question. this was returned automatically. i'll see what happened with it.

**Comment by RaananW** [comment]
> Is an empty picture for `public/img/playgroundsAndNMEs/pg-PCY1J-299.png` the expected result?

It's an audio demo. empty scene. https://playground.babylonjs.com/#pcy1j#299
@PirateJC - let's think about what to do with demos like this one.

**Comment by RaananW** [comment]
Merged because I wanted the doc-change to work already, but I agree - we need to address the playground issue. i'll add an issue for me

**Pull request merged**
