### PR TITLE
Improving documentation for Vertex Normals

### PR DESCRIPTION
**Pull request by thebravoman**
Looking at: "Table of Indices, Positions and Normals for Flat Shaded Box" there is a table.
In the table there are 24 rows. But when I run the playground example and add a few console logs it will produce a table with 36 rows.

Example - https://www.babylonjs-playground.com/#1H7L5C#64

Changing the table in the documentation to reflect the values produced by the example that is included with the documentation.

PR is based on discussion with Deltakosh at https://forum.babylonjs.com/t/vertex-normals-babylon-js-documentation-has-a-table-with-24-rows-and-they-probably-should-be-36/15603

### CODE REVIEW

**Comment by BabylonJSGuide** [comment]
Please hold off merging this PR. It is not the table that needs changing but the explanation. Each vertex for each face of the cube has a unique normal, 4 vertices per face, 6 faces on a cube so 24 unique normals. The 36 arises because because each face is split into two triangles and the two vertices at the end of each hypotenuse occur in both triangles adding an extra 12normals which are repeats of existing normals. I will re-write the documentation to make it clear we are talking about the unique normals.

**Comment by RaananW** [comment]
Thanks John (@BabylonJSGuide) , please let me know if I should close or merge (i assume close?)

**Comment by BabylonJSGuide** [comment]
By the way Guide is John not Jason. Please close. Also if you have not seen my last couple of Docs Update PMs on the forum please check them out as I need some advice. Than you.

**Comment by RaananW** [comment]
@BabylonJSGuide  - I know that! It was my very stupid mobile keyboard. Sorry...

**Comment by RaananW** [comment]
@thebravoman - docs were updated to represent the right information, please let us know if it now makes more sense

**Pull request closed without merging**
