### PR TITLE
Allow anchoring an image with H2 and H3 elements

### PR DESCRIPTION
**Pull request by RaananW**
The idea is to allow anchoring a title with an image before the H tag.

This is now supported on H2 and H3 tags. Usage:

Instead of `##` or `###` use

```html
<H2Image title="The title Of this thing" image="/img/linkToImage.jpg"/>

OR

<H3Image title="The title Of this thing" image="/img/linkToImage.jpg"/>
```

### CODE REVIEW

**Review by Popov72 — APPROVED** [review]

**Review by PatrickRyanMS — COMMENTED** [review]
I assume that along with title= and image=, we can also add an alt tag for the image as we would with any other HTML tag?

**Comment by RaananW** [comment]
> I assume that along with title= and image=, we can also add an alt tag for the image as we would with any other HTML tag?

The image's alt tag is the title, but i can add an override of needed

**Comment by PatrickRyanMS** [comment]
I think having the option of an alt tag override would be good. I can see cases where we may want the alt tag to be far more descriptive than what we want for the h2/h3 tag text.

**Comment by RaananW** [comment]
> I think having the option of an alt tag override would be good. I can see cases where we may want the alt tag to be far more descriptive than what we want for the h2/h3 tag text.

It shall be done 😎

**Comment by RaananW** [comment]
> I think having the option of an alt tag override would be good. I can see cases where we may want the alt tag to be far more descriptive than what we want for the h2/h3 tag text.

you can now add an optional `alt` parameter to override the alt for the image. if it is not provided, the title will be used.

**Review by Popov72 — APPROVED** [review]

**Review by PatrickRyanMS — APPROVED** [review]

**Pull request merged**
