### PR TITLE
Copy code

### PR DESCRIPTION
**Pull request by impurity-dev**
image
image
image

Feature Request: https://forum.babylonjs.com/t/copy-code-in-docs/41886

Added copy/paste functionality

### CODE REVIEW

**Review by RaananW — APPROVED** [review]
Wow, this is amazing. thank you very much!

I do want @PatrickRyanMS's opinion about the design, otherwise - looks amazing to me! :-)

**Comment by impurity-dev** [comment]
> I do want @PatrickRyanMS's opinion about the design, otherwise - looks amazing to me! :-)

No worries at all! Lemme know if something needs to change. I'm a potato with UI design, so I just kinda looked at ChatGPT and the MUI website. Mostly tried to emulate the MUI pattern

**Comment by RaananW** [comment]
> I'm a potato with UI design

You and me both! :-)

**Comment by PatrickRyanMS** [comment]
I think the states of the UI are fine, but we should use fluent icons to match with all of the other UI icons we use. Here are two fluent icons for copy and completed. Swapping these icons for the ones in this PR is all that is needed.

[fluent_copyIcons.zip](https://github.com/BabylonJS/Documentation/files/13478448/fluent_copyIcons.zip)

**Comment by impurity-dev** [comment]
image
image
@PatrickRyanMS Done 🚀

**Pull request merged**
