### PR TITLE
Updates to GUI docs to include HtmlMesh as another GUI option

### PR DESCRIPTION
**Pull request by ericwood73**

### CODE REVIEW

**Review by RaananW — CHANGES_REQUESTED** [review]
Is there a link for the resource? Somewhere to read about HtmlMesh? does it already exist in the page?

**Comment by ericwood73** [comment]
> Is there a link for the resource? Somewhere to read about HtmlMesh? does it already exist in the page?

I could add a link to the GitHub readme for HtmlMesh.

**Comment by ericwood73** [comment]
Or I could add a page for HtmlMesh to community extensions.  That would probably be better.

**Comment by RaananW** [comment]
Whatever you find better. Would be great to add a page for it, but if it is too much, a link to the repo would be great

**Comment by deltakosh** [comment]
up:)

**Review by RaananW — DISMISSED** [review]

**Comment by RaananW** [comment]
@ericwood73 - we want to merge this, have you made the adjustments?
Thanks :-)

**Comment by ericwood73** [comment]
No.  Sorry.  Will work on it today.

**Comment by ericwood73** [comment]
@RaananW I completed my updates.  Ready for review.

**Comment by RaananW** [comment]
You should add it to structure.json as well, as we don't take the directory structure as is. You can run `npm run build:local` (or yarn, of course), to make sure it compiles correctly.

**Review by RaananW — APPROVED** [review]
LGTM! will be merged once build is successful (after updating the structure file)

**Comment by ericwood73** [comment]
Copy.  I was editing in github, but I'll pull down and run the build.

**Comment by ericwood73** [comment]
@RaananW How do I get the error when building locally.  It just tells me it failed to build the extensions page, but it doesn't say why.  I added the page to structure.json and the build error on gui went away (or it's now hitting a different error because now it is looking at the extensions page).

**Comment by RaananW** [comment]
> @RaananW How do I get the error when building locally.  It just tells me it failed to build the extensions page, but it doesn't say why.  I added the page to structure.json and the build error on gui went away (or it's now hitting a different error because now it is looking at the extensions page).

The build will provide you with a reason. Might be an internal link missing. Which probably your link to the document from the page it is complaining about is incorrect

**Comment by ericwood73** [comment]
It doesn't give me any reason why it fails.  Just `Error: Export encountered errors on following paths:
        /[...id]: /communityExtensions/htmlMesh`.  I'll keep eliminating external references one by one until I find the one it is choking on.

**Comment by RaananW** [comment]
Have you pushed the structure.json update? i'm pulling the branch now

**Comment by RaananW** [comment]
Made a few changes to the PR (I hope I didn't push myself too much here...)

The way it is right now works as expected :-) I'll merge it once it is done building

**Comment by ericwood73** [comment]
Thanks.  I made the changes to structure and for some reason it wasn't building locally but I pulled your changes and now it works.

**Pull request merged**
