### PR TITLE
Display world axis

### PR DESCRIPTION
**Pull request by RolandCsibrei**
Hey!
I've changed the usage of the deprecated Mesh create functions to MeshBuilder and made the whole function TS friendly. There is a new example PG as well.

### CODE REVIEW

**Comment by RaananW** [comment]
Thanks a lot!
What are all of those images? are they missing somewhere? because I don't see any of them referenced in the changes made.

**Comment by RolandCsibrei** [comment]
Only a space character was I believe automatically deleted by the code formatter. No images in this article.

**Comment by RaananW** [comment]
I'm taking about the 10 images added to the PR

**Comment by RolandCsibrei** [comment]
What the hell... I'll make a new PR.

**Pull request closed without merging**
