### PR TITLE
GRL - new standard examples and advanced examples

### PR DESCRIPTION
**Pull request by RolandCsibrei**
Some new PGs and advanced examples page.

### CODE REVIEW

**Comment by RolandCsibrei** [comment]
The addpoints example will work after I create a GreasedLine PR. I started to add a third material type, SimpleMaterial. It will take some time to finish it, so the PR will be a bit delayed.

**Comment by RaananW** [comment]
there is a small conflict, and - is it ready to be merged, or would you rather merge after the code is available?

**Review by RaananW — APPROVED** [review]
LGTM, just resolve the conflict :-)

**Comment by RolandCsibrei** [comment]
Hello! Sorry for the late response. The emails from github started to land in the spam folder. I will add documentation for the simple greased line material (the code PR is ready) and resolve the conflict today.

**Comment by RaananW** [comment]
Is this ready to be merged?

**Comment by RolandCsibrei** [comment]
> Is this ready to be merged?

Sure

**Pull request merged**
