### PR TITLE
docs: remove `markAllAsDirty` in Material_plugins.md

### PR DESCRIPTION
**Pull request by yuqianma**
related discuss: https://forum.babylonjs.com/t/doc-markallasdirty-is-unnecessary-in-material-plugins/29494

### CODE REVIEW

**Comment by Popov72** [comment]
I think you should also update the example playgrounds to remove the reference and use `markAllDefinesAsDirty` instead.

**Comment by yuqianma** [comment]
> I think you should also update the example playgrounds to remove the reference and use `markAllDefinesAsDirty` instead.

Oh, right !

**Comment by yuqianma** [comment]
@Popov72  Done?

**Review by RaananW — APPROVED** [review]
LGTM, waiting on @Popov72

**Comment by Popov72** [comment]
That's ok for the PGs but you should also rename the pictures.

For eg, for `#GC63G5#3`, you should rename `public/img/playgroundsAndNMEs/pg-GC63G5-3.png` into `public/img/playgroundsAndNMEs/pg-GC63G5-16.png`.

**Review by deltakosh — APPROVED** [review]

**Comment by yuqianma** [comment]
@Popov72 
Images are renamed.

I thought images are generated automatically by CI. 😂 So what if these images have to be replaced? Run build?
Maybe there should be some commit guides.
At the begining I modified the code within github directly. Later I opened a codespace. It would be sweet to make the process easily. As some are just typos or tiny updates like this one.

**Comment by Popov72** [comment]
I think the picture is generated automatically locally, not on the build server: you would still have to commit and push it.

In the present case, as the PGs themselves have not changed, it's easier to simply rename the files.

**Comment by RaananW** [comment]
> @Popov72 Images are renamed.
> 
> I thought images are generated automatically by CI. 😂 So what if these images have to be replaced? Run build? Maybe there should be some commit guides. At the begining I modified the code within github directly. Later I opened a codespace. It would be sweet to make the process easily. As some are just typos or tiny updates like this one.

`npm run build:local` will generate the images.

**Comment by yuqianma** [comment]
Ready to merge?

**Pull request merged**
