### PR TITLE
Add simple lightmap example

### PR DESCRIPTION
**Pull request by carolhmj**

### CODE REVIEW

**Comment by sebavan** [comment]
Wonder if @PatrickRyanMS has a softer lightmap texture ?

**Comment by PatrickRyanMS** [comment]
@sebavan the only model I have that was set up to use lightmaps was https://forum.babylonjs.com/t/lightmaps-how-they-behave-in-sandbox-babylonjs/12357/3?u=patrickryan and it was using it as a shadow map only. No PG on this one. If you want to use this scene, I can quickly gather it together and make a PG, but I don't have anything else ready to go that uses lightmaps.

**Review by RaananW — APPROVED** [review]
Approved, but will let either @PatrickRyanMS or @sebavan merge it in case they have a better demo example

**Comment by RaananW** [comment]
I am merging this. if there is a better demo we can always improve this

**Pull request merged**
