### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by impurity-dev**
## 📓 Description
image

Dark mode, mostly because I wanted it. But for an extra boost, there was a request: https://forum.babylonjs.com/t/doc-dark-mode-request-for-solution/43193/6 😄. The toggle in the top right toggles between light and dark mode. This will store an item in the local storage once clicked as a user preference.

## ⚠️ Flicker
I setup the default color mode here:
```typescript
const prefersLightMode = useMediaQuery('(prefers-color-scheme: light)');
const [mode, setMode] = useState<PaletteMode>(prefersLightMode ? "light" : "dark");
```
to try and determine what the user wants. However, if the user has saved locally something different,
```typescript
useEffect(() => {
    const savedUserPreference = localStorage.getItem(THEME_PREFERENCE);
    if(savedUserPreference === 'light')
      setMode('light')
    else if(savedUserPreference === 'dark')
      setMode('dark')
  }, [])
```
this will fire onLoad. Unfortunately, this will cause a flicker and is a known annoyance in the approach. MUI has a CSS-theme-vars migration guide, that if this project moved to, would remove that. However, it felt like a nice-to-have/feature-request in the future, and too much work to do in this PR.

[MUI Context](https://mui.com/material-ui/experimental-api/css-theme-variables/migration/#3-prevent-dark-mode-flickering-in-server-side-applications)

---
❗❗❗Please take your time reviewing this. Lots of changes and I made a few based off assumptions of the setup today. I am happy to receive and incorporate any feedback, just lemme know what you want changed !

### CODE REVIEW

**Comment by RaananW** [comment]
Love it. Even with `prefers-color-scheme` support. Amazing work! :-)

Sorry, have to fetch @PatrickRyanMS again. But you have my approval for sure!

**Comment by impurity-dev** [comment]
> Sorry, have to fetch @PatrickRyanMS again. But you have my approval for sure!

You and him are gunna hate me for blasting off PRs the last few days 😭

**Comment by RaananW** [comment]
> > Sorry, have to fetch @PatrickRyanMS again. But you have my approval for sure!
> 
> You and him are gunna hate me for blasting off PRs the last few days 😭

On the contrary! :-)

**Comment by PatrickRyanMS** [comment]
I'm going to need to spend a little time with this one as I need to check the site in dark mode against accessibility guidelines. I will dig in and come up with any changes that are needed to meet the guidelines.

**Comment by RaananW** [comment]
Oh, and sorry for adding the conflict! had to add something at the root component.

**Comment by impurity-dev** [comment]
> Oh, and sorry for adding the conflict! had to add something at the root component.

No need to apologize. I'm positive that whatever you are doing is more important than dark mode docs 😆

**Comment by impurity-dev** [comment]
@PatrickRyanMS Hey man, is there anything/any-tool that I could run this through to help validate?

**Comment by PatrickRyanMS** [comment]
> @PatrickRyanMS Hey man, is there anything/any-tool that I could run this through to help validate?

https://github.khronos.org/glTF-Validator/

**Comment by PatrickRyanMS** [comment]
> @PatrickRyanMS Hey man, is there anything/any-tool that I could run this through to help validate?

Apologies, I had the wrong link on my clipboard. This is the tool you can use: https://microsoftedge.microsoft.com/addons/detail/accessibility-insights-fo/ghbhpcookfemncgoinjblecnilppimih

**Comment by impurity-dev** [comment]
@PatrickRyanMS Were you able to take a look at this yet? I have not, been swamped at work :/

**Comment by PatrickRyanMS** [comment]
> @PatrickRyanMS Were you able to take a look at this yet? I have not, been swamped at work :/

Same. I have one more push for a deliverable this week and then I should be able to open some time to look at it.

**Comment by impurity-dev** [comment]
> > @PatrickRyanMS Were you able to take a look at this yet? I have not, been swamped at work :/
> 
> Same. I have one more push for a deliverable this week and then I should be able to open some time to look at it.

Seems more than fair to me, appreciate it man :) best of luck

**Comment by impurity-dev** [comment]
@RaananW perhaps this could get merged, but with a new issue/task added to check the a11y stuff in the future? Would love to see this start adding value and perhaps getting feedback from the customers. Im even willing to tackle that a11y stuff, I just would prefer to iterate on it instead of making this PR any bigger, yk?

**Review by RaananW — APPROVED** [review]

**Comment by aWeirdo** [comment]
Can we have this updated so it defaults to light mode?
a lot of the text/link colors, box-shadows, etc are not suited for the dark background, 
it was a.. not very pleasant surprise 😄

**Comment by sebavan** [comment]
Same comment :-) @RaananW would be great to default to light mode ?

**Comment by RaananW** [comment]
It defaults to your system's settings. it was actually configured to be this way.

Maybe it would be good to know what bothers you (instead of defaulting to light mode) so we can fix it?

**Comment by sebavan** [comment]
ohhh strange 
image

Wondering if it takes the Windows one instead of the app one

**Comment by RaananW** [comment]
Hmmm...

Needs to be investigated. The site should be displayed in light colors in this case.

@impurity-dev - got a hint? Otherwise i'll investigate later this week

**Comment by impurity-dev** [comment]
@RaananW @sebavan @aWeirdo 

Apologies! After mulling this over, in retrospect i think this could have been better had I started with default light, and migrated to adding the media-query to use system setting AFTER dark mode was good to go. My intent was to get the ball rolling on this since the changes were large, and gain some early user feedback to act upon. Apologies for any disturbance. 😞 

However, now that I've already violated your vision with the  ✨initial✨  dark mode, I'd LOVE to get some _actionable_ user feedback on the dark mode on what could be improved! 🚀 You wont hurt my feelings, so be honest! (and to who ever stumbles on this thread later on).

In terms of the code itself, I wrote it to use system default *first*. Once you click, in the storage it will maintain a theme indicator which determines the preference. I'll look into this tomorrow a bit and see if I can determine whats up.

**Comment by sebavan** [comment]
Honestly it looks great !!! :-) 

I am just old and have trouble changing my habits lol

**Comment by impurity-dev** [comment]
@sebavan a "get off my lawn" moment for you? 😆

**Comment by PatrickRyanMS** [comment]
The one thing I am noticing is that when the doc site loads, I get a few frames of dark mode before it switches to light mode. It's a little jarring and I am wondering if we are rendering something and then checking for the system default rather than not rendering anything until we know what version to render?

**Comment by impurity-dev** [comment]
> The one thing I am noticing is that when the doc site loads, I get a few frames of dark mode before it switches to light mode. It's a little jarring and I am wondering if we are rendering something and then checking for the system default rather than not rendering anything until we know what version to render?

Yeah, its super unfortunate... I outlined the reason within the PR itself, but the flicker will always be there until a few upgrades are performed (as far as i can tell, with the current MUI version). But I'm planning to do that upgrade soon

**Comment by RaananW** [comment]
> > The one thing I am noticing is that when the doc site loads, I get a few frames of dark mode before it switches to light mode. It's a little jarring and I am wondering if we are rendering something and then checking for the system default rather than not rendering anything until we know what version to render?
> 
> Yeah, its super unfortunate... I outlined the reason within the PR itself, but the flicker will always be there until a few upgrades are performed (as far as i can tell, with the current MUI version). But I'm planning to do that upgrade soon

i'll try looking into that tomorrow. There should be a solution for this. (not too trivial with server-side rendering)

We are still using MUI styles, which is not actively developed. 

EDIT - #1054

**Comment by aWeirdo** [comment]
@impurity-dev i took some quick screenshots, i felt like that was the easiest method to point out the few flaws that remain, otherwise it's a great addition!

1. Missing box-shadows, it hurts the design of the docs and causes a lack of clear sections.
2. Deep Purple link/text colors become very "screaming" on a dark background 

babylonDocs

And i'd like to add that all my settings are default and it switches me to dark mode on all browsers until i toggle the light switch, so i don't think the system default thing is working properly. Windows 10 🤔

**Comment by impurity-dev** [comment]
@aWeirdo Duuueeede, thank you! Yeah good call. This will be interesting since this is actually generated via typedoc; although im sure theres a way to set theme. Im running win10 as well, theres a very real chance I just am bad at coding and it doesnt work as advertised! Ill take a look and try to replicate :)

**Pull request merged**
